name: Merge master to main

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper merge

      - name: Merge master into main
        run: |
          git config --global user.name "JonathanArroyaveGonzalez"
          git config --global user.email "arroyave3000g@gmail.com"
          git checkout main
          git merge master
          git push

